### ISSUE TITLE
Move IPFS addressing spec to ipfs/specs

### ISSUE THREAD

**Issue by lidel** [ipfs/specs#248]
The best and **up-to-date source of truth about IPFS addressing right now is in** [ADDRESSING.md](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) memo.

As more and more people add IPFS support to their software, especially on the web,
we should decrease noise and increase signal around addressing by adding proper technical spec doc to the [ipfs/specs](https://github.com/ipfs/specs) repo, as suggested in https://github.com/ipfs/specs/issues/138.

#### Timeline

- 2019:  
   - WIP on IPFS addressing (https://github.com/ipfs/go-ipfs/issues/5287, https://github.com/ipfs/in-web-browsers/issues/118)
   - WIP on libp2p addressing (https://github.com/libp2p/specs/pull/191)
- 2018: [ADDRESSING.md](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) memo is created as a techncial summary of [ipfs/specs/dweb-addressing](https://github.com/ipfs/specs/tree/addressing/dweb-addressing)
- 2018: [Suborigins](https://github.com/ipfs/in-web-browsers/issues/66) & [Subdomains](https://github.com/ipfs/in-web-browsers/issues/89)
- 2017-2018: [ipfs/specs/dweb-addressing](https://github.com/ipfs/specs/tree/addressing/dweb-addressing) branch with lots and lots of notes
- 2015-2017: Memo with Background on Address Scheme discussions: https://github.com/ipfs/specs/pull/152 
- 2017: Tackle identifying origins: ipfs/in-web-browsers/issues/6
- 2017: **The four stages of the upgrade path for path addressing** https://github.com/ipfs/specs/pull/152#issuecomment-284628862
- 2016: Support Custom Protocols in WebExtension https://github.com/ipfs-shipyard/ipfs-companion/issues/164
- 2015: First discussion about addressing schemes https://github.com/ipfs/go-ipfs/issues/1678

#### TODO

- [ ] create a new PR to `ipfs/specs` (consolidate technical content from Prior Art)
  (https://github.com/ipfs/specs/blob/master/DWEB_ADDRESSING.md, reuse https://github.com/ipfs/specs/pull/152)
    - [ ] PR should aim to close https://github.com/ipfs/specs/issues/138
    - [ ] close https://github.com/ipfs/specs/pull/139 and point at new PR
- [ ] ensure it covers `/ipns/` as well (https://github.com/ipfs/go-ipfs/issues/5287, https://github.com/ipfs/in-web-browsers/issues/118)
- [ ] get it merged to [ipfs/specs](https://github.com/ipfs/specs) repo 
- [ ] update `ADDRESSING.md` to point at the doc in [ipfs/specs](https://github.com/ipfs/specs)
- [ ] close remaining issues/PRs about addressing with comment pointing at document in specs repo (add links below so we don't forget)
  - [ ] https://github.com/ipfs/interface-js-ipfs-core/issues/287
  - [ ] https://github.com/ipfs/docs/issues/91
  - [ ] https://github.com/ipfs/go-ipfs/issues/1678
  - [ ] https://github.com/ipfs/in-web-browsers/issues/118
  - [ ] https://github.com/ipfs/specs/issues/138
  - [ ] https://github.com/ipfs/in-web-browsers/issues/6
- [ ] identify remaining content from Prior Art that could be extracted into [ipfs/blog](https://github.com/ipfs/blog/) post or less technical [ipfs/docs](https://github.com/ipfs/docs/issues/91)

cc https://github.com/ipfs/in-web-browsers/issues/118 https://github.com/ipfs/in-web-browsers/issues/3 ipfs/ipfs#227 ipfs/in-web-browsers#4 ipfs/in-web-browsers#28 https://github.com/ipfs/specs/pull/139 @autonome

**Comment by jchris** [comment]
Is this grammar a relevant resource? https://github.com/jonnycrunch/ipfs-uri-scheme/blob/master/application.md#3-uri-scheme-registration

**Comment by lidel** [comment]
I believe this grammar was created with intent to get IANA registration, but in the end was not needed because rules changed and IANA request we used had different form: https://github.com/fred-wang/iana-uri-schemes-provisional-registration-requests/blob/master/ipfs.txt
