### ISSUE TITLE
IPFS DHT Specification is  missing

### ISSUE THREAD

**Issue by lidel** [ipfs/specs#345]
This is a placeholder for missing specs.

## Problem

- No pecs for IPFS DHT exist.
- Kad DHT specs that live in https://github.com/libp2p/specs/tree/master/kad-dht and are currently focused on Peer routing only (scope limited to libp2p use of DHT).
- IPFS specifics such as how provider records and IPNS records are published  / resolved was removed from the mentioned specs, but should be still  in git history of that repo 

## TODO 
- [ ] see if we can salvage  any old content from https://github.com/libp2p/specs/tree/master/kad-dht
- [ ] decide if our spec is on top of libp2p one, or do we have our own, end-to-end specs 
- [ ] WRITE THE SPECS and get sign-off  from GO, JS and Rust impl.

**Comment by SgtPooki** [comment]
@lidel will this IPIP also include AcceleratedDHTClient spec? or should we create a separate issue for that?

**Comment by lidel** [comment]
tbd, not part of protocol per se, just an efficient way of architecting client.  

this is similar to Bitswap Sessions - could be an Appendix "Notes for implementers", or a separate file to avoid noise
