### ISSUE TITLE
IPIP: UnixFS and Gateway support for explicit MIME/Content-Type

### ISSUE THREAD

**Issue by lidel** [ipfs/specs#364]
This is a placeholder issue for creating IPIP to add support for storing explicit MIME/Content-Type in UnixFS DAG itself, and acting on it on Gateways.

## Context

UnixFSv2 never happened, but ability to explicitly specify `Content-Type`  was one of my asks: https://github.com/ipld/legacy-unixfs-v2/issues/11

Five years later we still guess `Content-Type` on gateways.
While it is fine for most of the time, but we should provide users with ability to explicitly set media type at the time of data onboarding.

Since 2018 we made some related development: we've added opt-in support for `mode` and `mtime` attributes. ~2020 (https://github.com/ipfs/specs/issues/217#issuecomment-582369839). Support for `mode` and `mtime`  was implemented in JS-IPFS a while ago, Kubo still has PR open (https://github.com/ipfs/go-unixfs/pull/117). 

Initial idea (details to be fleshed out in IPIP) is to introduce optional `mtype` similar way.

Ref.
- Media Type registry at IANA: https://www.iana.org/assignments/media-types/media-types.xhtml
  - IETF RFC https://www.rfc-editor.org/rfc/rfc2046.html

- Some examples how the same CID can be returned with different `Content-Type`: https://github.com/ipfs/in-web-browsers/issues/152
- Kubo Gateway guessing `Content-Type` based on filename and magic bytes: https://github.com/ipfs/kubo/blob/v0.17.0-rc2/core/corehttp/gateway_handler_unixfs_file.go#L55-L87
  - Gateway support for overriding filename: https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#filename-request-query-parameter
     - IPFS users leverage this for adjusting Content-Type when `/ipfs/cid` is requested without  any filename, but with built-in support for explicit content type we could make it "just work". 

## TODO

- [ ] wait until UnixFS specs land (#331)
- [ ] create IPIP against UnixFS specs that 
   - [ ] defines canonical way of storing explicit MIME (content/media type)  in UnixFS root dag-pb blocks.
   - [ ] modifies Gateway spec to disable mime-sniffing and use sanitized (ASCII-only) value from dag-pb in  `Content-Type` header
- [ ] Create reference implementation in Kubo
  - [ ] adds optional `--content-type`  to `ipfs add`
  - [ ] skip sniffing and set `Content-Type` header on gateway, if present

**Comment by lidel** [comment]
Need some help with historical context:

- UnixFS 1.5 added `Data.mode` and `Data.mtime` fields
  - JS support landed a while ago  (https://github.com/ipfs/js-ipfs-unixfs/pull/36). 
  -  GO support is in limbo, proposed in [this PR](https://github.com/ipfs/go-unixfs/pull/117/files#diff-f811e47a51ed792c9eea238f764391e1718822dbb40ab9308b3c552646476092)
- What we propose in this issue is "UnixFS 1.6" (tbd)
   - My initial idea was to add Content Type field as  `Data.ctype`..
   - ... but I've noticed there is an existing  `Metadata.MimeType` field  in  [`unixfs.proto`](https://github.com/ipfs/go-unixfs/blob/f455d36c5fd1bab0395f3c441f80cbd72454a180/pb/unixfs.proto)  already (seems to be not used for anything anywhere tho).

Feels like there is a reason why `Metadata` was not used for `mtime` and `mode` (see [js-ipfs-unixfs/unixfs.proto](https://github.com/ipfs/js-ipfs-unixfs/blob/f74a850c2c1aa28024f86ba12b589df733d7e4ca/packages/ipfs-unixfs/src/unixfs.proto))
  
@achingbrain @alanshaw do you remember why these fields landed in `Data` and not `Metadata`? Or who would be good person to ask?

**Comment by lidel** [comment]
Some thoughts in case someone wants to pick this up in the future:

The [UnixFS spec](https://specs.ipfs.tech/unixfs/) that merged in August 2025 has a legacy pb that already "reserves" a slot for this: `message Metadata { string MimeType = 1; }`, and `DataType Metadata = 3`, both marked "reserved for future use". Nothing implements either.

IIRC some of discussions we had, reusing that legacy `Metadata` node type is a trap. Implementations already disagree on how `Data_Metadata` behaves, which is why boxo returns early on it and points at #316. The shape with precedent is a new optional field on `Data`, after `mode` (7) and `mtime` (8), the same way UnixFS 1.5 added those.

Whichever shape, it is opt-in and changes the CID of anything that sets it, and it only pays off once gateways act on it, which is the #257 side.

So the IPIP is still unwritten, but the design space is small now: choose the field, define precedence against extension sniffing and the existing default, and add [gateway-conformance](https://github.com/ipfs/gateway-conformance) tests. Then implement it in both `boxo/gateway` and `@helia/verified-fetch`
